fix: Убрал вертикальный скролл в браузере Firefox
Studio-Yandex-Practicum/lomaya_baryery_frontend pull request #31
Opened 2023-03-16 02:18 UTC by Filin1985

Нашел следующее решение:
- нужно было добавить scrollbar-width: none;
Добавил данное свойство в root

2023-03-16 11:48 UTC, NikolaySmolov commented
Скролл в FF по прежнему есть. Как проверить?
На винде - будет видно сразу
На маке - включить отображение скролла Системные настройки - Оформление - Показывать полосы прокрутки - Всегда

2023-03-16 11:50 UTC, niksmo requested changes
Скролл по прежнему отображается в FF, написал в комментах как проверить

2023-03-16 13:42 UTC, NikolaySmolov requested changes
Решение будет таким 😉
.custom-scroll {
  scrollbar-width: thin;
  scrollbar-color: #939faebf transparent;
}

2023-03-17 06:27 UTC, Filin1985 commented
Добавил в common.css
.custom-scroll {
scrollbar-width: thin;
scrollbar-color: #939faebf transparent;
}

2023-03-17 07:18 UTC, NikolaySmolov approved these changes

2023-03-17 07:18 UTC, merged